# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9GnJV9sLrRLx1vrLj924sSbHTKPZak6
"""

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('data.csv')

df.head()

df.isnull().sum()

df['Age'].fillna(df['Age'].mean(), inplace=True)

df.duplicated().sum()

df = df.drop_duplicates()

df.dtypes

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

df['Name'] = df['Name'].str.upper()

df[df['Age'] < 0]

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df['Salary'] < (Q1 - 1.5 * IQR)) |
    (df['Salary'] > (Q3 + 1.5 * IQR))
]

outliers

df.info()

df.to_csv('cleaned_dataset.csv', index=False)

files.download('cleaned_dataset.csv')